#!/usr/bin/env python
# coding=utf-8
from sys import argv
import logging
from s3logs import S3Pusher

if __name__ == '__main__':
    if len(argv) > 1:
        if len(argv) > 2:
            if argv[1] == "-v":
                pusher = S3Pusher(argv[2])
                logging.getLogger().setLevel(logging.DEBUG)
            elif argv[2] == "-v":
                pusher = S3Pusher(argv[1])
                logging.getLogger().setLevel(logging.DEBUG)
            else:
                pusher = None
                logging.error("Usage %s [-v] config_file.conf" % argv[0])
                exit(2)
        else:
            if argv[1] == "-v":
                logging.error("Usage %s [-v] config_file.conf" % argv[0])
                exit(2)
            pusher = S3Pusher(argv[1])

        pusher.push_candidates()
    else:
        logging.error("Usage %s [-v] config_file.conf" % argv[0])
        exit(1)
